export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
